### ISSUE TITLE
Open F12 and use tools ，The page is obviously stuck.

### ISSUE THREAD

**Issue by warmthsea** [vuejs/devtools-next#211] opened 2024-01-30 08:20 UTC
# Test content: switching pages or page interaction
- windows 11 （RAM 32G）（multiple computers）
- chrome: 120
- vue: 3.4.3
- vite: 4.5.1
- tool: last
- tool show active page component: 600
- project modules: 3600

(other project test about the same ↓)（ _gif contrast is relatively poor）_

## 1. F12 + tools  （degree of lag：4）

![screenshots](https://github.com/vuejs/devtools-next/assets/45450994/3ecfc87c-52ff-46fb-8ddd-a4d17127a0ee)

## 2. only F12      （degree of lag：1）

![screenshots](https://github.com/vuejs/devtools-next/assets/45450994/da0e5483-aae5-44c8-a8fa-26317cd73ea2)

## 3. only tools     （degree of lag：1）

![screenshots](https://github.com/vuejs/devtools-next/assets/45450994/47615188-7d80-4f4c-ade8-606e3f016a9c)

## 4. none       （degree of lag：0）

![screenshots](https://github.com/vuejs/devtools-next/assets/45450994/7d460a92-bdb2-4cd8-b801-2237f426d223)

**Comment by webfansplz** [comment] 2024-01-30 08:53
Seems you can also use the Vue DevTools Chrome Extensions, can you disable it and try again?

**Comment by warmthsea** [comment] 2024-01-30 09:05
## 5. off  Chrome Extensions，F12 + tools

![screenshots](https://github.com/vuejs/devtools-next/assets/45450994/8256ebd3-6d07-4519-8286-7ef0a4025d84)

## 6. off  Chrome Extensions，F12 

![screenshots](https://github.com/vuejs/devtools-next/assets/45450994/67fc261f-87ad-411b-bed7-9ffbf30e590f)

**Comment by adamdehaven** [comment] 2024-01-30 18:24
> Seems you are also use the Vue DevTools Chrome Extensions, can you disable it and try again?

I'm also seeing the same issue in my host apps.

I don't think disabling the Chrome extension is a valid solution - I have to work between multiple projects; some use the new beta dev tools, some must use the old Chrome extension.

**Comment by webfansplz** [comment] 2024-01-31 04:43
> > Seems you are also use the Vue DevTools Chrome Extensions, can you disable it and try again?
> 
> I'm also seeing the same issue in my host apps.
> 
> I don't think disabling the Chrome extension is a valid solution - I have to work between multiple projects; some use the new beta dev tools, some must use the old Chrome extension.
> 
> Disabling the extension _does_ seem to resolve the issue, but ideally the Vite plugin could resolve without this being needed

Try disabling Chrome Extension just to confirm where the issue is coming from.  Are there performance issues when they are enabled at the same time, and when Chrome DevTools is not opened (via F12)?

**Comment by warmthsea** [comment] 2024-01-31 04:47
It doesn't seem to be related.

Tool & Chrome extension

**Comment by adamdehaven** [comment] 2024-01-31 12:32
For me, the page only becomes unresponsive when the Chrome extension is also enabled. 

Multiple engineers on my team have confirmed at least in our repos, the issue is resolved when the Chrome extension is disabled.

**Comment by alexzhang1030** [comment] 2024-01-31 13:08
Does everything work fine when using an older version of Devtools?

**Comment by warmthsea** [comment] 2024-01-31 13:11
> Does everything work fine when using an older version of Vue Devtools browser extension?

Sometimes it's very stuck and rarely used.

**Comment by alexzhang1030** [comment] 2024-01-31 13:24
Looks like there is not **too** much data... I'm unsure of the root reason, but we will test some cases to find it.

**Comment by warmthsea** [comment] 2024-01-31 13:26
> Looks like there is not **too** much data... I'm unsure of the root reason, but we will test some cases to find it.

I will provide more data when I have time.

**Comment by alexzhang1030** [comment] 2024-01-31 13:27
> > Looks like there is not **too** much data... I'm unsure of the root reason, but we will test some cases to find it.
> 
> I will provide more data when I have time.

Thanks, looking forward to it.

**Comment by SeaAster** [comment] 2024-04-25 03:26
Is this issue fixed now?

**Comment by alexzhang1030** [comment] 2024-06-16 13:44
We have recently implemented several improvements through #429 and #268, which have significantly enhanced speed.

For users still experiencing slow performance, we recommend upgrading to version v7.3.0. Please test with this version to see if the issue is resolved.

If the problem persists after upgrading, let us know, and we will continue to investigate further.

**Comment by warmthsea** [comment] 2024-06-16 14:05
> We have recently implemented several improvements through #429 and #268, which have significantly enhanced speed.
> 
> 
> 
> For users still experiencing slow performance, we recommend upgrading to version v7.3.0. Please test with this version to see if the issue is resolved.
> 
> 
> 
> If the problem persists after upgrading, let us know, and we will continue to investigate further.

If I have time, I will participate in the test. Thank you for your work.

**Comment by warmthsea** [comment] 2024-06-20 09:03
I switched to the same branch as above and upgraded the tools version. Here is a test preview. When I opened F12, I saw obvious lag.


### 1. Not Use Tools

![screenshots](https://github.com/vuejs/devtools-next/assets/45450994/d6d1f499-aa0d-4ca1-8ef9-015dfa609b89)

### 2. Use Tools - `vite-plugin-vue-devtools@7.3.2`

![screenshots](https://github.com/vuejs/devtools-next/assets/45450994/41f41102-eea5-468d-9e31-00e0f408d70a)

**Closed** 2024-09-03 16:22 UTC
Labels: help wanted, perf
