### ISSUE TITLE
Open component in editor opens Sublime Text instead of VSCode

### ISSUE THREAD

**Issue by franzgollhammer** [vuejs/devtools-next#367] opened 2024-05-06 07:46 UTC
## Description:
My default editor for .vue files is VSCode. If i have Sublime Text and VSCode open at the same time, if i try to open a component in the editor via the component inspector tool it instead opens the file in Sublime Text.

## Expected:
Component should open in VSCode.

## Observed:
- Component opens in Sublime Text if both editors are open.
- If "only" VSCode is open it opens up correctly in VSCode.

## Steps to reproduce:
- Set "open file with" default program to vscode via finder.
- Open Sublime text.
- Open Vscode.
- Open a component via the vue-devtools component inspector.

### OS: 
Darwin 23.4.0 Darwin Kernel Version 23.4.0: Fri Mar 15 00:10:42 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T6000 arm64

**Comment by alexzhang1030** [comment] 2024-05-07 01:21
Duplicate of #341

**Closed by alexzhang1030** 2024-05-07 01:21 UTC
Labels: duplicate, usage
